###############################################################################
# Configuration for Microsoft NNI
# Reference: https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html
#
# Run the NNI experiment:
#   nnictl create --config $HOME/projects/bioseq-learning/src/configs/baseline_masked_genome_model_config.yml --debug --port 8080
#
# Some must-read notes:
# - sshKeyPath demands PEM formatting or whatnot
# - paths in YAML file cannot use environment variables
# - codeDir will be copied over to worker machines and cannot be empty
# - localhost (as nniManagerIp) cannot receive log from worker machines over http
# - CUDA_VISIBLE_DEVICES will be set for the first instruction in trail command only
#
###############################################################################

authorName: "Xiaotian Duan (xduan7)"
experimentName: "baseline masked genome model prediction with transformer"

# maxExecDuration: 10d
# maxTrialNum: 1000
trainingServicePlatform: remote
searchSpacePath: "baseline_masked_genome_model_search_space.json"
useAnnotation: false
multiThread: true

tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
    parallel_optimize: True
    constant_liar_type: min


trial:
  command: CUDA_DEVICE_ORDER=PCI_BUS_ID PYTHONPATH="${HOME}/projects/bioseq-learning:${PYTHONPATH}" ${HOME}/anaconda3/envs/bioseq/bin/python ${HOME}/projects/bioseq-learning/src/baseline_masked_genome_model.py
  gpuNum: 2  # number of GPUs used for a single trial
  codeDir: nni_code_dir

###############################################################################
# manager: localhost
# worker: lambda4.cels.anl.gov
###############################################################################

#logDir: /Users/xduan7/projects/bioseq-learning/logs/nni_experiments
#nniManagerIp: localhost
#trialConcurrency: 4
#
#machineList:
#- ip: lambda4.cs.uchicago.edu
#  port: 22
#  username: xduan7
#  sshKeyPath: ~/.ssh/id_rsa_pem
#  maxTrialNumPerGpu: 1
#  useActiveGpu: false

###############################################################################
# manager: lambda0.cels.anl.gov
# worker: lambda0.cels.anl.gov, lambda1.cels.anl.gov, etc.
#
# to use local browser dashboard:
# (1) run 'ssh -C2qTnN -D 8080 lambda0' on local machine
# (2) set up the browser proxy (firefox)
#     - check manual proxy configuration
#     - SOCKS Host=localhost, port=8080
#     - check SOCKS v5
# (3) use address lambda0.cels.anl.gov:8080, assuming the port is 8080
#
# alternatively, one could run 'sshuttle -r lambda0 0.0.0.0/0' to replace
#  step (1) and (2) above, but the connection seems to be unstable
###############################################################################

logDir: /homes/duan/projects/bioseq-learning/logs/nni_experiments
nniManagerIp: lambda0.cels.anl.gov
trialConcurrency: 20
# the log collection part doesn't seem to work ...
# not only that, the paths to logs would be hidden in the log collection mode
#logCollection: http

machineList:
  - ip: lambda0.cels.anl.gov
    port: 22
    username: duan
    sshKeyPath: ~/.ssh/id_rsa_pem
    maxTrialNumPerGpu: 1
    # gpuIndices: 2,3,4,5,6,7
    useActiveGpu: false
  - ip: lambda1.cels.anl.gov
    port: 22
    username: duan
    sshKeyPath: ~/.ssh/id_rsa_pem
    maxTrialNumPerGpu: 1
    # gpuIndices: 2,3,4,5,6,7
    useActiveGpu: false
  - ip: lambda2.cels.anl.gov
    port: 22
    username: duan
    sshKeyPath: ~/.ssh/id_rsa_pem
    maxTrialNumPerGpu: 1
    # gpuIndices: 2,3,4,5,6,7
    useActiveGpu: false
  - ip: lambda3.cels.anl.gov
    port: 22
    username: duan
    sshKeyPath: ~/.ssh/id_rsa_pem
    maxTrialNumPerGpu: 1
    # gpuIndices: 2,3,4,5,6,7
    useActiveGpu: false
  - ip: lambda4.cels.anl.gov
    port: 22
    username: duan
    sshKeyPath: ~/.ssh/id_rsa_pem
    maxTrialNumPerGpu: 1
    # gpuIndices: 2,3,4,5,6,7
    useActiveGpu: false
